### ISSUE TITLE
对node的版本有要求么

### ISSUE THREAD

**Issue by Neilyoz** [xhuz/ts.dll#1]
12.16.1比较新的版本没有办法进行npm安装，想请问下支持的node版本是多少

**Comment by xhuz** [comment]
理论来说10.13以上版本都应该能用的，你可以提供一下报错信息

**Comment by Neilyoz** [comment]
已经好了，是windows-build-tools的问题，重新装了一下就好了。

**Comment by Neilyoz** [comment]
> 理论来说10.13以上版本都应该能用的，你可以提供一下报错信息

已经好了，是windows-build-tools的问题，重新装了一下就好了。
