### ISSUE TITLE
你好 我对nodejs 写辅助有点兴趣给个联系方式方便交流吗

### ISSUE THREAD

**Issue by huanglei1991** [xhuz/ts.dll#2]
你好 我对nodejs 写辅助有点兴趣给个联系方式方便交流吗
最近想给一个挂机游戏 弄挂机脚本，我会java TypeScript 但是对写外挂没有经验 想要和你交流下 
我的QQ525839616

**Comment by xhuz** [comment]
你想交流什么？开发脚本，和开发程序没什么大的差别。就是调调api就好了

**Comment by huanglei1991** [comment]
比如 因为想要加上客户端UI 和 electron 集成ok嘛 
还有就是为什么 只能32位上使用
还有就是天使插件的具体使用文档和教程有资料能共享下吗 谢谢

**Comment by xhuz** [comment]
脚本加UI完全没问题，至于为什么只能在32位上面跑，是因为我拿到的是32位的dll。我尝试自己编译64位的dll，但是插件代码里面包含了一些汇编代码，编译64位是不支持在c中内嵌汇编的。至于文档已经包含在仓库里面了

**Comment by huanglei1991** [comment]
谢谢 如果你不觉得麻烦的话 我遇到细节问题的时候可以请教你下吗
其实希望能用通信软件请教一些 杂七杂八的问题 ╮(╯▽╰)╭
如果不愿意的话 我就只能在这边提问了 因为我对脚本开发没有经验 所以可能问的问题比较傻 请多担待

**Comment by xhuz** [comment]
我加你qq吧。关闭这个issue了
